s = set([2,35,1,5,6,8,21])
print("Set :",s)
s.add(1234)
print("Add member(s) to the set ", s)
s.remove(1234)
print("Remove the added items ",s)
print("find the maximum and minimum value of the set ", max(s))
s.clear()
print("Remove all the items in the set ", s)